---
title: "Hi! My Name is Nicole Hua"
---

Welcome to my website! For my CV, please visit [About](about.qmd)

**All About Me!**

I am in my fourth year at the University of Waterloo and when I graduate, I would like to pursue further education for a master's in Developmental Psychology and Education.

I am currently volunteering at Pivot Point in Milton where I assist behaviour analysts in supporting adults with diverse abilities. I am expanding my knowledge on ABA therapeutic services, 1:1 sessions with clients, and individualized program planning.

**My Interests**

I am currently working on building my research experience after gaining a great appreciation for research and data analysis. I have taken data analysis and research courses, providing me with a foundation for working with research.

The discipline of psychology I am the most interested in is developmental psychology. I began working with children at a young age and have since expanded my experiences to working individuals from diverse demographics. The more I interact with varying populations—such as children, older adults, and indiviuals with cognitive impairments—the more I realize the importance of understanding and reearching human development. 
<br><br>

<center>**Contacts and CV**<center> 
Phone number: [(905) 462-1332](tel:19054621332)<br>
Email: [nhua\@uwaterloo.ca](mailto:nhua@uwaterloo.ca)<br>
Linkedin: [Nicole Hua](https://www.linkedin.com/in/nicole-hua-923aab2a8/)<br>

