---
title: "Nicole's Amazing Website <3 :)"
---

**All About Me!** \vspace{1em}

I am in my fourth year at the University of Waterloo and when I Graduate, I would like to pursue further education for a master's in Developmental Psychology and Education.

I am currently volunteering at Pivot Point in Milton, where I assist behaviour analysts in supporting adults with diverse abilities.

**My Interests**\vspace{1em}

As of right now, I don't have research experience but I am making an effort to change that! (if you are interested in having a research assistant, please see my cv below).

The discipline of psychology that I am most interested is developmental psychology. I have loved working with children since I was a child, and the more I engage with children now, the more I realize the importance of researching and understanding development.

**To Get in Contact with Me**\vspace{1em} If you are interested in having either a volunteer or a research assistant, please reach out to me at any of the contacts I have listed below.\vspace{1em}

Phone number: (905) 462-1332. \vspace{1em}

Email: [nhua\@uwaterloo.ca](mailto:nhua@uwaterloo.ca)\vspace{1em}

Linkedin: [Nicole Hua](https://www.linkedin.com/in/nicole-hua-923aab2a8/)